baseurl = "https://yao.dk/"
languageCode = "en-us"
title = "Yaoxin"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
enableEmoji = true
hasCJKLanguage = true


[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页/Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于/About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "标签/Tags"
    url = "/tags/"
    weight = 3

[params]
    footer = "&copy; [Yaoxin Xiang](https://www.yao.dk) | [Github](https://github.com/xiangyx)"
    favicon = "favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
